# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter : postgresql
  encoding: unicode
  pool    : 5

development:
  <<: *default
  database: nway-website_development
  username: postgres
  password: postgres
  host    : localhost
  port    : 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: debug5, debug4, debug3, debug2, debug1, log, notice, warning, error, fatal, and panic

test:
  <<: *default
  database: nway-website_test
  username: postgres
  password: postgres
  host    : localhost
  port    : 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: debug5, debug4, debug3, debug2, debug1, log, notice, warning, error, fatal, and panic

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  #schema_search_path: myapp,sharedapp,public
  #min_messages: debug5, debug4, debug3, debug2, debug1, log, notice, warning, error, fatal, and panic
